# Generated by Django 6.1 on 2026-08-15 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=250)),
                ('city', models.CharField(blank=True, max_length=150)),
                ('job_description', models.TextField()),
                ('job_url', models.URLField(blank=True)),
                ('source', models.CharField(choices=[('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('stepstone', 'StepStone'), ('xing', 'XING'), ('company', 'Company Website'), ('other', 'Other')], default='other', max_length=30)),
                ('score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('decision', models.CharField(choices=[('APPLY', 'Apply'), ('STRETCH', 'Stretch'), ('SKIP', 'Skip')], max_length=20)),
                ('employer_type', models.CharField(blank=True, max_length=100)),
                ('zeitarbeit_risk', models.BooleanField(default=False)),
                ('strong_matches', models.JSONField(blank=True, default=list)),
                ('gaps', models.JSONField(blank=True, default=list)),
                ('risks', models.JSONField(blank=True, default=list)),
                ('recommended_cv', models.CharField(blank=True, max_length=200)),
                ('do_not_claim', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('not_applied', 'Not Applied'), ('applied', 'Applied'), ('interview', 'Interview'), ('rejected', 'Rejected'), ('offer', 'Offer'), ('withdrawn', 'Withdrawn')], default='not_applied', max_length=30)),
                ('applied_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
