# Generated by Django 6.1 on 2026-08-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='follow_up_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='decision',
            field=models.CharField(blank=True, choices=[('APPLY', 'Apply'), ('STRETCH', 'Stretch'), ('SKIP', 'Skip')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='recommended_cv',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
