# Generated by Django 6.1 on 2026-08-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_coverletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverletter',
            name='signature_image',
            field=models.FileField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='coverletter',
            name='signature_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='coverletter',
            name='signature_type',
            field=models.CharField(choices=[('typed', 'Typed Signature'), ('uploaded', 'Uploaded Signature')], default='typed', max_length=20),
        ),
    ]
