# Generated by Django 6.1 on 2026-08-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_coverletter_signature_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverletter',
            name='recipient_city',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='coverletter',
            name='recipient_company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='coverletter',
            name='recipient_contact',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='coverletter',
            name='recipient_postal_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='coverletter',
            name='recipient_street',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
