# Generated by Django 6.1 on 2026-08-15 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('relocation', models.BooleanField(default=False)),
                ('education', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True)),
                ('strong_skills', models.TextField(blank=True)),
                ('basic_skills', models.TextField(blank=True)),
                ('languages', models.TextField(blank=True)),
                ('do_not_claim', models.TextField(blank=True)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('fa', 'فارسی')], default='en', max_length=2)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], default='free', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
