# Generated by Django 6.1 on 2026-08-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_professional_summary_certification_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.AddField(
            model_name='languageentry',
            name='original_level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='do_not_claim',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('unclassified', 'Not Classified'), ('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='unclassified', max_length=30),
        ),
        migrations.AddField(
            model_name='skill',
            name='source',
            field=models.CharField(choices=[('professional', 'Professional Experience'), ('education', 'Education'), ('project', 'Personal Project'), ('course', 'Course / Certification'), ('self_taught', 'Self-taught'), ('unspecified', 'Not Specified')], default='unspecified', max_length=30),
        ),
        migrations.AlterField(
            model_name='languageentry',
            name='level',
            field=models.CharField(choices=[('unspecified', 'Not Specified'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('native', 'Native')], default='unspecified', max_length=20),
        ),
    ]
