# Generated by Django 6.1 on 2026-08-17 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveredJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('arbeitnow', 'Arbeitnow'), ('arbeitsagentur', 'Bundesagentur für Arbeit'), ('indeed', 'Indeed'), ('stepstone', 'StepStone'), ('linkedin', 'LinkedIn'), ('company', 'Company Website'), ('other', 'Other')], default='other', max_length=40)),
                ('external_id', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('company', models.CharField(blank=True, max_length=250)),
                ('location', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(max_length=1500)),
                ('remote', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-published_at', '-first_seen_at'],
                'indexes': [models.Index(fields=['source', 'published_at'], name='discovery_d_source_a4c38c_idx'), models.Index(fields=['is_active'], name='discovery_d_is_acti_d7cb5d_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='unique_discovered_job_source_id')],
            },
        ),
        migrations.CreateModel(
            name='JobSearchTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('radius_km', models.PositiveIntegerField(default=50)),
                ('remote', models.BooleanField(default=True)),
                ('exclude_zeitarbeit', models.BooleanField(default=False)),
                ('minimum_match_score', models.DecimalField(decimal_places=1, default=6.0, max_digits=3)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_search_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='JobRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('match_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('viewed', 'Viewed'), ('saved', 'Saved'), ('analyzed', 'Analyzed'), ('not_interested', 'Not Interested')], default='new', max_length=30)),
                ('recommended_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='discovery.discoveredjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_recommendations', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='discovery.jobsearchtarget')),
            ],
            options={
                'ordering': ['-recommended_at', '-match_score'],
            },
        ),
        migrations.AddConstraint(
            model_name='jobsearchtarget',
            constraint=models.UniqueConstraint(fields=('user', 'title', 'location'), name='unique_job_search_target'),
        ),
        migrations.AddIndex(
            model_name='jobrecommendation',
            index=models.Index(fields=['user', 'status'], name='discovery_j_user_id_fb539d_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrecommendation',
            index=models.Index(fields=['user', 'recommended_at'], name='discovery_j_user_id_5817ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobrecommendation',
            constraint=models.UniqueConstraint(fields=('user', 'job'), name='unique_job_recommendation_per_user'),
        ),
    ]
